# Generated by Django 3.0.4 on 2020-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstPage', '0003_auto_20200423_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
